### ISSUE TITLE
Cant use the worldedit

### ISSUE THREAD

**Issue by SettingDust** [UraniumMC/Uranium#4]
Caused by: com.sk89q.worldedit.extension.platform.NoCapablePlatformException: No platform was found supporting PERMISSIONS
at com.sk89q.worldedit.extension.platform.PlatformManager.queryCapability(PlatformManager.java:169) ~[worldedit-bukkit-6.1.jar:?]
at com.sk89q.worldedit.extension.platform.PlatformManager.createProxyActor(PlatformManager.java:251) ~[worldedit-bukkit-6.1.jar:?]
at com.sk89q.worldedit.extension.platform.CommandManager.handleCommand(CommandManager.java:208) ~[worldedit-bukkit-6.1.jar:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_201]
at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[worldedit-bukkit-6.1.jar:?]
at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[worldedit-bukkit-6.1.jar:?]

**Comment by xe5700** [comment]
Plz use latest one build
No platform was found supporting PERMISSIONS maybe you need vault plugin and a permission plugin like luckperms

**Comment by SettingDust** [comment]
> Plz use latest one build
> No platform was found supporting PERMISSIONS maybe you need vault plugin and a permission plugin like luckperms

I use the GroupManager to manage permission, and I plugin the Vault plugin. XD

I'm tring the B20 at present

chinese here..

**Comment by SettingDust** [comment]
It's seems like the B20 is fix it. Sorry. Thx.
